# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    services:
      postgres:
         image: postgres
         env:
           POSTGRES_PASSWORD: postgres
           options: >-
             --health-cmd pg_isready
             --health-interval 10s
             --health-timeout 5s
             --health-retries 5
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run createdb
    - run: npm run populatedb
    - run: npm test
    - run: npm run coverage
    - run: npm run dropdb
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres
        SECRET: githubactions
        PORT: 3000
